# Base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy requirements.txt to the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . .

# Expose a port (if needed)
EXPOSE 5000

# Define the command to run the application
CMD ["python", "app.py"]
